name: Matrix
on: push

jobs: 
  node-version:
    strategy:
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_versio: [6,8,14]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v2
        with:
           node-version: ${{ matrix.node_versin }}
      - name: Log node version 
        run: node -v
